name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
       
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/LoginTest/scripts" >> $GITHUB_ENV

    - name: Set Environment Variables
      run: |
        echo "PYTHONPATH=$PWD/login_test/homeobjects:$PWD/LoginTest/scripts/setup_mongodb.py" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://127.0.0.1:27017/test_db" >> $GITHUB_ENV

    - name: Wait for MongoDB to be ready
      run: |
        until nc -zv localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is ready"
    - name: Make run_tests.sh executable
      run: chmod +x ./run_tests.sh
      
    - name: Run tests
      run: ./run_tests.sh
    
    - name: Run Selenium Tests
      run: ./run_tests.sh
      continue-on-error: true  
      id: selenium_test

    - name: Show Test Results Log
      if: failure()
      run: cat  test_results.log .log  # Modify as per the actual log file path

    - name: Send Failure Email Notification
      if: failure()
      run: |
          echo "Tests failed! Sending email notification..."
          python send_email_notification.py "Tests failed on release push"
    