name: Release Push CI

on:
 
  push:
    branches: [main]
     
jobs:
  release_push:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
       
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/LoginTest/scripts" >> $GITHUB_ENV

    - name: Set Environment Variables
      run: |
        echo "PYTHONPATH=$PWD/login_test/homeobjects:$PWD/LoginTest/scripts/setup_mongodb.py" >> $GITHUB_ENV
        echo "MONGO_URI=mongodb://127.0.0.1:27017/test_db" >> $GITHUB_ENV

    - name: Wait for MongoDB to be ready
      run: |
        until nc -zv localhost 27017; do
          echo "Waiting for MongoDB to start..."
          sleep 1
        done
        echo "MongoDB is ready"
    - name: Make run_tests.sh executable
      run: chmod +x ./run_tests.sh
      

    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Download the release documentation (for example, from a URL or repo)
    - name: Download Release Document
      run: |
        echo "Downloading release document..."
        curl -o release_doc.pdf https://example.com/release-doc.pdf
    
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
    
    

    
    - name: Set PYTHONPATH
      run: |
          echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/LoginTest/scripts" >> $GITHUB_ENV
  
    - name: Set Environment Variables
      run: |
          echo "PYTHONPATH=$PWD/login_test/homeobjects:$PWD/LoginTest/scripts/setup_mongodb.py" >> $GITHUB_ENV
          echo "MONGO_URI=mongodb://127.0.0.1:27017/test_db" >> $GITHUB_ENV
  
    - name: Wait for MongoDB to be ready
      run: |
          until nc -zv localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 1
          done
          echo "MongoDB is ready"
    - name: Make run_tests.sh executable
      run: chmod +x ./run_tests.sh
        

    # Step 4: Run the shell script to invoke the Selenium scripts
    - name: Run Shell Script using PowerShell
      shell: pwsh
      run: |
          echo "Running the Selenium tests..."
          chmod +x ./run_tests.sh
          bash ./run_tests.sh    # Call bash explicitly from pwsh
  

    # Step 5: Show 
    - name: Display Test Results Log
      run: |
        echo "Displaying test results log..."
        cat test_results.log

    # Step 6: Send Failure Email Notification if tests failed
    - name: Send Failure Email Notification
      if: failure()  # Trigger this step only if previous steps failed
      run: |
        echo "Tests failed! Sending email notification..."
        python send_email_notification.py "Tests failed on release push"

