name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install MongoDB tools
      run: |
        sudo apt-get update
        # Add the MongoDB GPG key
        wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
        # Add the MongoDB repository
        echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
        sudo apt-get update
        # Install mongo-tools via mongodb-org-tools
        sudo apt-get install -y mongodb-org-tools


    - name: Seed MongoDB with test data
      run: |
        docker exec mongodb mongo "mongodb://127.0.0.1:27017/sampleupload" --eval 'db.users.insertOne({"username": "testuser", "password": "testpass", "baseurl": "https://demo.filebrowser.org/login?redirect=/files/", "is_valid": true})'
    - name: Set up ChromeDriver and Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Run Selenium Tests
      env:
        MONGO_URI: "mongodb://127.0.0.1:27017/sampleupload"
      run: |
        python -m unittest discover -s login_testcases -p "valid.py"
