name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up ChromeDriver and Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Configure MongoDB Test Data
      run: |
        python  scripts/setup_mongodb.py # Run the setup script

    - name: Run Selenium Tests
      env:
        MONGO_URI: "mongodb://127.0.0.1:27017/sampleupload"
      run: |
        python -m unittest discover -s login_testcases -p "valid.py"
