name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on pushes with tags that start with "v", like v1.0 or v2.1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js # Optional: Only if you're using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag that triggered the workflow
          release_name: ${{ github.ref_name }}
          body: "Automatic release for ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: filename.zip  # Replace with your file or artifact
          asset_name: filename.zip  # Replace with the name you want the asset to have
          asset_content_type: application/zip
