name: Release Download CI

on:
  release:
    types: [published]  # Trigger on new release publication

jobs:
  download_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: List release assets
      run: |
        gh release view ${{ github.event.release.tag_name }} --json assets --jq '.assets[].name'

    - name: Download release assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p downloaded_release_assets
        gh release download ${{ github.event.release.tag_name }} --dir downloaded_release_assets

    # Optional: List downloaded files
    - name: List downloaded files
      run: |
        echo "Downloaded files:"
        ls downloaded_release_assets
